language: python
python:
  - "3.6.2"

services:
  - postgresql

before_script:
  - psql -c "create database users;" -U postgres
  - python manage.py makemigrations authentication
  - python manage.py makemigrations profiles
  - python manage.py makemigrations articles
  - python manage.py migrate

install:
  - pip install -r requirements.txt

script:
  - coverage run --source=authors/ manage.py test

after_success:
  - coveralls
